export const arrayItems = [
  { text: 'at', link: '/array/at' },
  { text: 'chunk', link: '/array/chunk' },
  { text: 'uniq', link: '/array/uniq' },
  { text: 'uniqBy', link: '/array/uniq-by' },
  { text: 'difference', link: '/array/difference' },
  { text: 'differenceWith', link: '/array/difference-with' },
  { text: 'intersection', link: '/array/intersection' },
  { text: 'intersectionWith', link: '/array/intersection-with' },
  { text: 'xor', link: '/array/xor' },
  { text: 'xorWith', link: '/array/xor-with' },
  { text: 'groupBy', link: '/array/group-by' },
  { text: 'find', link: '/array/find' },
  { text: 'shuffle', link: '/array/shuffle' },
  { text: 'removeItem', link: '/array/remove-item' },
  { text: 'toggleItem', link: '/array/toggle-item' },
  { text: 'removeArrayBlank', link: '/array/remove-array-blank' },
  { text: 'removeArrayEmpty', link: '/array/remove-array-empty' },
  { text: 'normalizeToArray', link: '/array/normalize-to-array' },
]
