export const elementItems = [
  { text: 'requestAnimationFrame', link: '/element/request-animation-frame' },
  { text: 'cancelAnimationFrame', link: '/element/cancel-animation-frame' },
  { text: 'raf', link: '/element/raf' },
  { text: 'doubleRaf', link: '/element/double-raf' },
  { text: 'getStyle', link: '/element/get-style' },
  { text: 'getRect', link: '/element/get-rect' },
  { text: 'inViewport', link: '/element/in-viewport' },
  { text: 'getParentScroller', link: '/element/get-parent-scroller' },
  { text: 'getAllParentScroller', link: '/element/get-all-parent-scroller' },
  { text: 'preventDefault', link: '/element/prevent-default' },
  { text: 'getScrollTop', link: '/element/get-scroll-top' },
  { text: 'getScrollLeft', link: '/element/get-scroll-left' },
  { text: 'classes', link: '/element/classes' },
  { text: 'createNamespaceFn', link: '/element/create-namespace-fn' },
]
