export const utilItems = [
  { text: 'mitt', link: '/util/mitt' },
  { text: 'motion', link: '/util/motion' },
  { text: 'copyText', link: '/util/copy-text' },
  { text: 'download', link: '/util/download' },
  { text: 'storage', link: '/util/storage' },
  { text: 'classes', link: '/util/classes' },
  { text: 'createNamespaceFn', link: '/util/create-namespace-fn' },
  { text: 'raf', link: '/util/raf' },
  { text: 'doubleRaf', link: '/util/double-raf' },
  { text: 'requestAnimationFrame', link: '/util/request-animation-frame' },
  { text: 'cancelAnimationFrame', link: '/util/cancel-animation-frame' },
  { text: 'inViewport', link: '/util/in-viewport' },
  { text: 'preventDefault', link: '/util/prevent-default' },
  { text: 'getStyle', link: '/util/get-style' },
  { text: 'getRect', link: '/util/get-rect' },
  { text: 'getScrollTop', link: '/util/get-scroll-top' },
  { text: 'getScrollLeft', link: '/util/get-scroll-left' },
  { text: 'getParentScroller', link: '/util/get-parent-scroller' },
  { text: 'getAllParentScroller', link: '/util/get-all-parent-scroller' },
  { text: 'prettyJSONObject', link: '/util/pretty-JSON-object' },
  { text: 'tryParseJSON', link: '/util/try-parse-JSON' },
]
